version: '3.8'
<<<<<<< HEAD
services:
  ollama:
    image: ollama/ollama:latest
    restart: always
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
=======

services:
  # 1. THE LLM ENGINE
  vllm-engine:
    image: vllm/vllm-openai:latest
    env_file:
    - .env
    restart: unless-stopped
    container_name: vllm-engine
    ports:
      - "8005:8005"
    runtime: nvidia
    environment:
      # --- ADD YOUR HF TOKEN HERE ---
      - HF_API_TOKEN=${HF_TOKEN}
      - VLLM_API_KEY=${VLLM_API_KEY}
    volumes:
      # This mounts your host's HF cache so the container doesn't re-download the model
      - ~/.cache/huggingface:/root/.cache/huggingface
>>>>>>> dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
<<<<<<< HEAD
              capabilities: ["gpu"]
              count: all
    # Optionally for compatibility with Compose versions <3.9:
    runtime: nvidia  
    networks:
      - appnet
    command: serve

  streamlit:
    image: streamlit_llama_service
    build: .
    container_name: streamlit_app
    restart: always
    ports:
      - "8501:8501"
    environment:
      - BASE_URL=http://ollama:11435
    depends_on:
      - ollama
    networks:
      - appnet

volumes:
  ollama_data:

networks:
  appnet:
=======
              count: 1
              capabilities: [gpu]
    command: >
      --model meta-llama/Llama-3.2-3B-Instruct
      --dtype auto
      --api-key ${VLLM_API_KEY}
      --port 8005
      --host 0.0.0.0
      --gpu-memory-utilization 0.30
      --max-model-len 32768

  # 2. THE STREAMLIT UI
  streamlit-ui:
    build: .
    restart: unless-stopped
    container_name: streamlit-gptforyouth
    ports:
      - "8505:8505"
    environment:
      - RUNNING_IN_DOCKER=true
      # 172.17.0.1 is usually the host IP in Docker's default bridge network
      - HOST_IP=172.17.0.1
    depends_on:
      - vllm-engine
>>>>>>> dev
