version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all
    # Optionally for compatibility with Compose versions <3.9:
    runtime: nvidia  
    networks:
      - appnet
    command: serve

  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - appnet

volumes:
  ollama_data:

networks:
  appnet:
